"""Client — the main async context manager interface.

Usage::

    async with Client(storage=DiskStorage("/downloads")) as client:
        torrent = await client.add_torrent_file("archlinux.iso.torrent")
        await client.download(torrent.info_hash)
"""

from __future__ import annotations

import asyncio
import os
from collections.abc import Mapping
from pathlib import Path
from types import TracebackType

import attrs

from .network import AddressFamily, NetworkConfig, resolve_families
from .peer import PeerConnection, PeerInfo, generate_peer_id
from .piece import PieceTracker
from .storage.base import StorageBackend
from .torrent import InfoHash, TorrentMeta, parse_torrent_bytes, parse_torrent_file
from .tracker import AnnounceRequest, TrackerError, http_announce

# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

type TorrentHandle = InfoHash
"""Opaque handle used to reference a loaded torrent."""

# ---------------------------------------------------------------------------
# Client configuration
# ---------------------------------------------------------------------------


@attrs.frozen
class ClientConfig:
    """Immutable configuration for :class:`Client`."""

    listen_port: int = 6881
    """Port to listen for incoming peer connections."""

    max_peers: int = 50
    """Maximum simultaneous peer connections per torrent."""

    peer_id: bytes = attrs.field(factory=generate_peer_id)
    """Our 20-byte peer ID (generated by default)."""

    request_timeout: float = 30.0
    """Seconds to wait for a block before re-requesting."""

    network: NetworkConfig = attrs.field(factory=NetworkConfig)
    """Network configuration (address families, LSD, bind addresses)."""


# ---------------------------------------------------------------------------
# Torrent session — internal per-torrent state
# ---------------------------------------------------------------------------


class _TorrentSession:
    """Internal mutable state for a single loaded torrent."""

    def __init__(self, meta: TorrentMeta, storage: StorageBackend) -> None:
        self.meta = meta
        self.storage = storage
        self.tracker = PieceTracker(
            piece_length=meta.info.piece_length,
            total_length=meta.total_length,
            pieces_raw=meta.info.pieces_raw,
        )
        self.peers: dict[tuple[str, int], PeerConnection] = {}
        self.task: asyncio.Task[None] | None = None


# ---------------------------------------------------------------------------
# Client
# ---------------------------------------------------------------------------


class Client:
    """Async context manager for BitTorrent operations.

    Parameters
    ----------
    storage:
        A :class:`~aiobt.storage.base.StorageBackend` implementation.
    config:
        Optional :class:`ClientConfig` (defaults are sensible).

    Example
    -------
    ::

        async with Client(storage=DiskStorage("/dl")) as client:
            t = await client.add_torrent_file("file.torrent")
            await client.download(t.info_hash)
    """

    def __init__(
        self,
        storage: StorageBackend,
        config: ClientConfig | None = None,
    ) -> None:
        if not isinstance(storage, StorageBackend):
            raise TypeError(
                f"storage must satisfy StorageBackend protocol, "
                f"got {type(storage).__name__}"
            )
        self._storage = storage
        self._config = config or ClientConfig()
        self._sessions: dict[InfoHash, _TorrentSession] = {}
        self._running = False
        self._server: asyncio.Server | None = None

    # ----- async context manager --------------------------------------------

    async def __aenter__(self) -> Client:
        self._running = True
        return self

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None:
        self._running = False

        # Stop listening
        if self._server is not None:
            self._server.close()
            await self._server.wait_closed()
            self._server = None

        # Cancel all torrent tasks
        for session in self._sessions.values():
            if session.task is not None and not session.task.done():
                session.task.cancel()

        # Wait for tasks to finish
        tasks = [s.task for s in self._sessions.values() if s.task is not None]
        if tasks:
            await asyncio.gather(*tasks, return_exceptions=True)

        # Disconnect all peers
        for session in self._sessions.values():
            for peer in session.peers.values():
                await peer.disconnect()

        # Close storage for each session
        for session in self._sessions.values():
            await session.storage.close()

        self._sessions.clear()

    # ----- public API -------------------------------------------------------

    async def add_torrent_file(self, path: str | Path) -> TorrentMeta:
        """Load a ``.torrent`` file and prepare storage.

        Returns the parsed :class:`~aiobt.torrent.TorrentMeta`.
        """
        self._check_running()
        meta = parse_torrent_file(str(path))
        return await self._register(meta)

    async def add_torrent_bytes(self, data: bytes) -> TorrentMeta:
        """Load a torrent from raw bencoded *data*."""
        self._check_running()
        meta = parse_torrent_bytes(data)
        return await self._register(meta)

    async def download(self, info_hash: InfoHash) -> None:
        """Download a torrent to completion.

        Blocks until all pieces are downloaded and verified, or the
        client is shut down.

        .. todo:: Full download loop with peer management.
        """
        self._check_running()
        session = self._get_session(info_hash)

        # Announce to tracker
        tracker_urls = session.meta.tracker_urls()
        if not tracker_urls:
            raise ValueError("torrent has no tracker URLs")

        request = AnnounceRequest(
            info_hash=info_hash,
            peer_id=self._config.peer_id,
            port=self._config.listen_port,
            left=session.meta.total_length,
            event="started",
        )

        # Try trackers until one works
        peers = []
        for url in tracker_urls:
            try:
                if url.startswith("http"):
                    response = await http_announce(url, request)
                    peers = list(response.peers)
                    break
            except TrackerError, OSError:
                continue

        # TODO: connect to peers, request pieces, verify, write to storage
        raise NotImplementedError(
            "download loop not yet implemented — "
            f"found {len(peers)} peers from tracker"
        )

    async def seed(self, info_hash: InfoHash) -> None:
        """Seed a completed torrent.

        .. todo:: Implement seeding (accept connections, serve pieces).
        """
        self._check_running()
        session = self._get_session(info_hash)
        raise NotImplementedError("seeding not yet implemented")

    def get_progress(self, info_hash: InfoHash) -> float:
        """Return download progress as a fraction [0.0, 1.0]."""
        return self._get_session(info_hash).tracker.progress

    def list_torrents(self) -> list[TorrentMeta]:
        """Return metadata for all loaded torrents."""
        return [s.meta for s in self._sessions.values()]

    # ----- internal ---------------------------------------------------------

    async def _register(self, meta: TorrentMeta) -> TorrentMeta:
        """Register a torrent and prepare its storage."""
        if meta.info_hash in self._sessions:
            return meta

        session = _TorrentSession(meta=meta, storage=self._storage)
        await self._storage.open(meta.total_length, meta.info.piece_length)
        self._sessions[meta.info_hash] = session
        return meta

    def _get_session(self, info_hash: InfoHash) -> _TorrentSession:
        try:
            return self._sessions[info_hash]
        except KeyError:
            raise KeyError(f"no torrent with info hash {info_hash.hex()}") from None

    def _check_running(self) -> None:
        if not self._running:
            raise RuntimeError("Client must be used as an async context manager")
